server:
  port: 2604

spring:
  profiles.active: mysql
  datasource:
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 30000
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

security:
  oauth2:
    resource:
      jwt:
        key-value: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
---
spring:
  profiles: mysql
  datasource:
    driver-class-name: ${datasource.driver-class-name:com.mysql.jdbc.Driver}
    url: ${datasource.url:jdbc:mysql://localhost:3306/gamers_dynamic?characterEncoding=utf-8&com.mysql.jdbc.faultInjection.serverCharsetIndex=224}
    username: ${datasource.username:root}
    password: ${datasource.password:111111}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration/mysql
    table: schema_version

